In [1]:
# libraries
import os
import pandas as pd
from cryptography.fernet import Fernet

In [2]:
# explore the data
trends_quanlitative = pd.read_csv('trendmart_customer_persona_qualitative.csv')
trends_quantitative = pd.read_csv('trendmart_customer_persona_quantitative.csv')

In [3]:
# head of quanlitative
trends_quanlitative.head()

,Customer_ID,Goals and Aspirations,Pain Points and Challenges,Interest and Hobbies,Lifestyle and Values,Decision Making triggers
0,CUST1,Travel the world,Limited access to services,Sports,Community-driven,Discounts and offers
1,CUST2,Travel the world,Lack of career opportunities,Cooking,Environmentally conscious,Social media influence
2,CUST3,Start a business,Health issues,Fitness,Career-focused,Brand reputation
3,CUST4,Better health and fitness,High living costs,Fitness,Community-driven,Social media influence
4,CUST5,Education advancement,Technology barriers,Sports,Adventurous,Discounts and offers

In [4]:
# head of quantitative
trends_quantitative.head()

,Customer_ID,Name,Age,Gender,Location,Education Level,Occupation,Annual Income,Marital Status,Product Name,...,Online Purchase Frequency,Offline Purchase Frequency,Communication Preference,Technology Usage,Average Order Value,NPS Score,Customer Lifespan Years,Marketing Spend,Total Purchases,Revenue Generated
0,CUST1,Aarav Sharma,34,Male,Rural,Post Graduate,IT Professional,986983,Divorced,T-shirt,...,1,8,Social,Low,874,6,3.3,14362,9,7866
1,CUST2,Shreya Sen,53,Female,Urban,Undergraduate,Engineer,383060,Married,Handbag,...,6,2,Phone,Low,3861,3,1.3,37194,50,193050
2,CUST3,Suresh Nair,44,Male,Rural,PhD,Consultant,872961,Divorced,Smartphone,...,1,6,Social,High,737,3,3.4,10676,14,10318
3,CUST4,Shreya Sen,20,Female,Rural,Graduate,Marketing Manager,1449393,Single,Wrist Watch,...,3,9,Email,Medium,3852,9,5.9,39210,14,53928
4,CUST5,Neha Bhatia,43,Female,Rural,Graduate,Marketing Manager,1275043,Divorced,Refrigerator,...,2,3,Phone,Low,3626,4,7.2,48542,17,61642

In [7]:
# merge data
trends_mart = pd.merge(trends_quanlitative, trends_quantitative, on = 'Customer_ID', how = 'inner')
trends_mart.head()

,Customer_ID,Goals and Aspirations,Pain Points and Challenges,Interest and Hobbies,Lifestyle and Values,Decision Making triggers,Name,Age,Gender,Location,...,Online Purchase Frequency,Offline Purchase Frequency,Communication Preference,Technology Usage,Average Order Value,NPS Score,Customer Lifespan Years,Marketing Spend,Total Purchases,Revenue Generated
0,CUST1,Travel the world,Limited access to services,Sports,Community-driven,Discounts and offers,Aarav Sharma,34,Male,Rural,...,1,8,Social,Low,874,6,3.3,14362,9,7866
1,CUST2,Travel the world,Lack of career opportunities,Cooking,Environmentally conscious,Social media influence,Shreya Sen,53,Female,Urban,...,6,2,Phone,Low,3861,3,1.3,37194,50,193050
2,CUST3,Start a business,Health issues,Fitness,Career-focused,Brand reputation,Suresh Nair,44,Male,Rural,...,1,6,Social,High,737,3,3.4,10676,14,10318
3,CUST4,Better health and fitness,High living costs,Fitness,Community-driven,Social media influence,Shreya Sen,20,Female,Rural,...,3,9,Email,Medium,3852,9,5.9,39210,14,53928
4,CUST5,Education advancement,Technology barriers,Sports,Adventurous,Discounts and offers,Neha Bhatia,43,Female,Rural,...,2,3,Phone,Low,3626,4,7.2,48542,17,61642

In [12]:
# trends_mart to csv
trends_mart.to_csv('trends_mart.csv', index = False)

In [8]:
# generate key
key = Fernet.generate_key()

In [9]:
# store it in file
with open('filekey.key', 'wb') as f:
  f.write(key)

In [10]:
# read the key
with open('filekey.key', 'rb') as f:
  key = f.read()

In [11]:
# store it in fernet
fernet = Fernet(key)

In [13]:
# open the file in binary
with open('trends_mart.csv', 'rb') as f:
  data = f.read()

In [14]:
# encryption
encryption = fernet.encrypt(data)

In [15]:
# Overwrite the data
with open('trends_mart.csv', 'wb') as f:
  f.write(encryption)

In [16]:
# see the encrypted data
trends = pd.read_csv('trends_mart.csv')

In [17]:
trends.head()

Empty DataFrame

In [18]:
from google.colab import files

In [19]:
files.download('trends_mart.csv')

In [20]:
files.download('filekey.key')